[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/translation/start"
  to = "/.netlify/functions/translation-start"
  status = 200
  force = true

[[redirects]]
  from = "/api/translation/status/*"
  to = "/.netlify/functions/translation-status/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/translation/file/*"
  to = "/.netlify/functions/translation-file/:splat"
  status = 200
  force = true